# Generated by Django 3.0.5 on 2020-10-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbuddy', '0002_auto_20201030_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesscenter',
            name='fitnesscenter_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
